

define = -DAMIGALIBSELF=""

modules = retroFreeSprite.cpp \
			retroLoadSprite.cpp

all: $(modules:.cpp=.o)
	ar -rsc retromodelib.a $(modules:.cpp=.o) 


%.o: %.cpp
		g++ $(define) -c $(@:.o=.cpp) -o $@


clean:
		rm *.o