#!/bin/sh

mv retroCircle.c retroCircle.cpp
mv retroCircleFilled.c retroCircleFilled.cpp
mv retroClearVideo.c retroClearVideo.cpp
mv retroCloseScreen.c retroCloseScreen.cpp
mv retroColorRange.c retroColorRange.cpp
mv retroCycleColorsDown.c retroCycleColorsDown.cpp
mv retroCycleColorsUp.c retroCycleColorsUp.cpp
mv retroCycleOff.c retroCycleOff.cpp
mv retroDeleteFlash.c retroDeleteFlash.cpp
mv retroDmaVideo.c retroDmaVideo.cpp
mv retroDrawFrame.c retroDrawFrame.cpp
mv retroDrawVideo.c retroDrawVideo.cpp
mv retroEllipse.c retroEllipse.cpp
mv retroFadeScreen.c retroFadeScreen.cpp
mv retroFill.c retroFill.cpp
mv retroFlash.c retroFlash.cpp
mv retroFreeFrame.c retroFreeFrame.cpp
mv retroFreeSprite.c retroFreeSprite.cpp
mv retroFreeSpriteObject.c retroFreeSpriteObject.cpp
mv retroFreeSpriteObjects.c retroFreeSpriteObjects.cpp
mv retroFreeVideo.c retroFreeVideo.cpp
mv retroGetSprite.c retroGetSprite.cpp
mv retroLine.c retroLine.cpp
mv retroLoadABKSprite.c retroLoadABKSprite.cpp
mv retroLoadSprite.c retroLoadSprite.cpp
mv retroModeBadVideoSync.c retroModeBadVideoSync.cpp
mv retroOpenScreen.c retroOpenScreen.cpp
mv retroOrBAR.c retroOrBAR.cpp
mv retroOrBarRounded.c retroOrBarRounded.cpp
mv retroOrBitmapBlit.c retroOrBitmapBlit.cpp
mv retroOrBlit.c retroOrBlit.cpp
mv retroOrBox.c retroOrBox.cpp
mv retroOrCircle.c retroOrCircle.cpp
mv retroOrCircleFilled.c retroOrCircleFilled.cpp
mv retroOrFill.c retroOrFill.cpp
mv retroOrLine.c retroOrLine.cpp
mv retroOrScreenBlit.c retroOrScreenBlit.cpp
mv retroOrStar.c retroOrStar.cpp
mv retroOrTriangle.c retroOrTriangle.cpp
mv retroPasteSprite.c retroPasteSprite.cpp
mv retroPixel.c retroPixel.cpp
mv retroPoint.c retroPoint.cpp
mv retroPolyGonArray.c retroPolyGonArray.cpp
mv retroPolyGon.c retroPolyGon.cpp
mv retroPolyLine.c retroPolyLine.cpp
mv retroRainbow.c retroRainbow.cpp
mv retroRainbowColorRange.c retroRainbowColorRange.cpp
mv retroRain.c retroRain.cpp
mv retroScreenBlit.c retroScreenBlit.cpp
mv retroScreenClone.c retroScreenClone.cpp
mv retroScreenColor.c retroScreenColor.cpp
mv retroScreenDetach.c retroScreenDetach.cpp
mv retroScreenOffset.c retroScreenOffset.cpp
mv retroScreenToBack.c retroScreenToBack.cpp
mv retroScreenToFront.c retroScreenToFront.cpp
mv retroSetRainbow.c retroSetRainbow.cpp
mv retroSetVideoColor.c retroSetVideoColor.cpp
mv retroShift.c retroShift.cpp
mv retroSprite.c retroSprite.cpp
mv retroStar.c retroStar.cpp
mv retroThickLine.c retroThickLine.cpp
mv retroTriangle.c retroTriangle.cpp
mv retroXorBAR.c retroXorBAR.cpp
mv retroXorBarRounded.c retroXorBarRounded.cpp
mv retroXorBitmapBlit.c retroXorBitmapBlit.cpp
mv retroXorBox.c retroXorBox.cpp
mv retroXorCircle.c retroXorCircle.cpp
mv retroXorCircleFilled.c retroXorCircleFilled.cpp
mv retroXorLine.c retroXorLine.cpp
mv retroXorScreenBlit.c retroXorScreenBlit.cpp
mv retroXorTriangle.c retroXorTriangle.cpp
mv retroZoom.c retroZoom.cpp
